language: python
python:
  - "3.4"
  - "3.5"
# command to install dependencies
install:
  - python setup.py install
  - pip install numpy pandas scikit-learn
# command to run tests
script:
  - nosetests
