language: python

python:
  - "3.4"
  - "3.5"

addons:
  apt:
    packages:
    - libblas-dev
    - liblapack-dev
    - gfortran

before_install:
  - pip install -U pip

install:
  - travis_wait travis_retry pip install -r requirements-dev.txt
  - travis_retry pip install python-coveralls
  - travis_retry python setup.py dev

script:
  - nosetests

cache:
  - apt
  - directories:
    - $HOME/.cache/pip
